### ISSUE TITLE
Is the package still in development?

### ISSUE THREAD

**Issue by Perangelot** [patrickt/tree-sitter-org#1]
I use org-mode in combination with org-ref for my writings, but font-lock-mode is just incredibly slow and I thought about changing to tree-sitter. At the moment, org-mode is not supported, but if I understand this package correctly, this is exactly what it does, right? Is the package still in development?

**Comment by patrickt** [comment]
This is an _extremely_ early stage parser. It’s not abandoned, but it’s in no way complete (since Org is whitespace-sensitive, it probably requires a custom lexer, which I haven’t begun), and even if it was it would still require some glue on the emacs-tree-sitter side. Patches welcome!
